### ISSUE TITLE
feat: support .github/workflows/test.yml

### ISSUE THREAD

**Issue by exKAZUu** [WillBooster/wbfy#128]
```
on:
  pull_request:
    branches:
      - '**'
      - '!renovate/**'
  push:
    branches:
      - 'master'
      - 'renovate/**'
    paths-ignore:
      - 'docs/**'
      - '**.md'
```

`master` should be `main` ?
